### ISSUE TITLE
Enumerating instructions

### ISSUE THREAD

**Issue by cdonovick** [phanrahan/peak#3]
It would be convenient if there was a way to enumerate possible instructions.

desired behavior:
```Python3
for op in application: 
  for inst in Inst:
    alu_res, res_p, irq = PE(inst, *smt_bitvectors)
    solver.assert(alu_res != op.smt)
    if not solver.sat:
      #mapping found
      ...
```

This would be pretty easy to implement if all parts of an instruction were Enum as Enums are iterable.
```Python3
def enumerate(Inst : typing.Type[Product]):
  return itertools.product(*(x for x in Inst.__annotations__.values()))
```

**Comment by phanrahan** [comment]
Neat idea.

The two base types are Enum and Bits. We can iterate over those.

The two derived types are Product and Sum. We can also enumerate them.

Should be easy to do.

**Comment by phanrahan** [comment]
@cdonovick can we close this issue?
