### ISSUE TITLE
Refactoring types into separate module

### ISSUE THREAD

**Issue by leonardt** [phanrahan/peak#4]
It occurred to me that using the peak types like `Product` and `Bits(n)` would be useful in a broader context, such as the Python implementation of SIlica coroutines.  In our continued effort to converge the interfaces of various sub systems, I would propose moving the generic types in Peak into a separate repo/module, say `hwtypes` which could be used by various systems. This `hwtypes` repo could also include `BitVector`.

Thoughts? I remember discussing that `Bits(n)` was eventually going to be moved into `bit_vector`, so I think this proposal aligns with that idea, but broadens it from a `bit_vector` package into a more general `hwtypes` package.  Also, there's no existing pypi package called hwtypes, so I went ahead and reserved it!

**Comment by phanrahan** [comment]
How close are we to closing this issue?

**Comment by cdonovick** [comment]
The current implementation of Product, Sum, and Tuple are fairly restrictive in their type checking.  We should discuss the possibility of moving them and Peak having define their own restrictive mixins.
